version: "3.3"
services:
  database:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-root-pwd
      - MYSQL_DATABASE=magento
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:5
    environment:
      - PMA_HOST=database
    ports:
      - 3080:80
  elasticsearch:
    image: elasticsearch:7.9.3
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms768m -Xmx768m"
  magento:
    build:
      context: ./magento
    depends_on:
      - database
      - elasticsearch
    ports:
      - 3090:80
    volumes:
      - ./shared:/shared
